export default {
	login: 'andrew-george',
	id: 95014217,
	node_id: 'U_kgDOBanNSQ',
	avatar_url: 'https://avatars.githubusercontent.com/u/95014217?v=4',
	gravatar_id: '',
	url: 'https://api.github.com/users/andrew-george',
	html_url: 'https://github.com/andrew-george',
	followers_url: 'https://api.github.com/users/andrew-george/followers',
	following_url:
		'https://api.github.com/users/andrew-george/following{/other_user}',
	gists_url: 'https://api.github.com/users/andrew-george/gists{/gist_id}',
	starred_url:
		'https://api.github.com/users/andrew-george/starred{/owner}{/repo}',
	subscriptions_url: 'https://api.github.com/users/andrew-george/subscriptions',
	organizations_url: 'https://api.github.com/users/andrew-george/orgs',
	repos_url: 'https://api.github.com/users/andrew-george/repos',
	events_url: 'https://api.github.com/users/andrew-george/events{/privacy}',
	received_events_url:
		'https://api.github.com/users/andrew-george/received_events',
	type: 'User',
	site_admin: false,
	name: 'Andrew George',
	company: null,
	blog: '',
	location: 'Alexandria, Egypt',
	email: null,
	hireable: null,
	bio: null,
	twitter_username: null,
	public_repos: 5,
	public_gists: 0,
	followers: 1,
	following: 0,
	created_at: '2021-11-25T06:25:17Z',
	updated_at: '2022-11-07T19:49:18Z',
}
